version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "unicorn-inventory-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-9afr036x01pe"
s3_prefix = "unicorn-inventory-app"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = []
